import React, { useState, useEffect } from "react";
import type { GetServerSideProps } from "next";
import Head from "next/head";
import { Box } from "@chakra-ui/react";
import BottomBarLayout from "@/layouts/BottomBarLayout";
import CategorySlider from "@/components/ContentSlider/CategorySlider";
import ServicesSlider from "@/components/ContentSlider/ServicesSlider";
import ScrollableLists from "@/components/Lists/ScrollableLists";
import AppBar from "@/components/AppBar/AppBar";
import { FiMenu, FiBell } from "react-icons/fi";
import SearchInput from "@/elements/TextField/SearchInput";
import { useParams, useSearchParams } from "next/navigation";
import { foodType } from "@/Interfaces";

export const getServerSideProps: GetServerSideProps<{
  result: any;
}> = async () => {
  console.log(process.env);
  const response = await fetch(`${process.env.BASE_PATH_FRONTEND}/api/food`);
  const result = await response.json();
  return { props: { result } };
};

function ServiceDetails(props: any) {
  const { result } = props;
  const [products, setProducts] = useState([]);
  const [categories, setCategories] = useState([
    { name: "All" },
    {
      id: "11",
      image: "",
      name: "Biriyani",
    },
    { name: "Pizza" },
    { name: "Burger" },
    { name: "Milk Shakes" },
    { name: "Mojito" },
  ]);
  const [categorySelected, setSelectedCategory] = useState("All");

  useEffect(() => {
    setProducts(result);
  }, [result]);

  useEffect(() => {
    console.log(categorySelected);
  }, [categorySelected]);

  return (
    <>
      <Head>
        <title>Restaurant Details</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Box className="flex" height={"100vh"}>
        <AppBar
          prefix={
            <FiMenu
              style={{
                fontSize: "1.4rem",
              }}
            />
          }
          brandName="Dominos Pizza"
          suffix={
            <FiBell
              style={{
                fontSize: "1.4rem",
              }}
            />
          }
        />
        <Box height={10}></Box>
        <CategorySlider
          data={categories}
          selected={categorySelected}
          handleSelect={setSelectedCategory}
        />
        <Box height={5}></Box>
        <Box
          id="today-special"
          paddingInlineStart={"15px"}
          boxSizing="border-box"
        >
          <ServicesSlider
            heading="Today Special"
            data={products.filter((d: foodType) => d.isSpecial)}
          />
        </Box>
        <Box height={5}></Box>
        <Box padding={"0 15px"} boxSizing="border-box">
          <SearchInput placeholder="Search your Favourite Food" />
        </Box>
        <Box height={5}></Box>
        <Box padding={"0 15px"} boxSizing="border-box">
          <ScrollableLists
            heading="Today Menu"
            data={
              categorySelected === "All"
                ? products
                : products.filter(
                    (d: foodType) => d.foodCategory.name === categorySelected
                  )
            }
          />
        </Box>
      </Box>
    </>
  );
}

ServiceDetails.PageLayout = BottomBarLayout;

export default ServiceDetails;
