import React from "react";
import Head from "next/head";
import { Box } from "@chakra-ui/react";
import BottomBarLayout from "@/layouts/BottomBarLayout";

function Restaurant() {
  return (
    <Box className="flex">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1>Restaurant Page</h1>
    </Box>
  );
}

Restaurant.PageLayout = BottomBarLayout;

export default Restaurant;
