import React from "react";
import BottomBarLayout from "@/layouts/BottomBarLayout";
import { Box, Text } from "@chakra-ui/react";
import Head from "next/head";

function Cart() {
  return (
    <Box className="flex">
      <Head>
        <title>Dominos Cart</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Text>Cart</Text>
    </Box>
  );
}

Cart.PageLayout = BottomBarLayout;

export default Cart;
